name: Daily Penguin Prediction

on:
  push:
    branches:
      - Docker
  pull_request:
    branches:
      - Docker
  schedule:
    - cron: '30 07 * * *'
    - cron: '20 18 * * *'
  workflow_dispatch:

permissions:
  contents: write  # Explicit permission to write to repository contents

jobs:
  predict:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run prediction
        run: python scripts/prediction-api-script.py

      - name: Update index.html with latest prediction data
        run: |
          # Assuming the prediction data is saved in data/predictions/latest.json
          prediction_data=$(cat data/predictions/latest.json)
          # Use a templating tool or script to inject the prediction data into index.html
          # For example, using 'envsubst' to replace placeholders in a template
          envsubst < templates/index.html.template > index.html

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add index.html data/predictions/
          git diff --staged --quiet || git commit -m "Update penguin prediction for $(date +'%Y-%m-%d')"
          git push || (git pull --rebase && git push)
