name: Daily Penguin Prediction

on:
  push:
    branches:
      - Docker
  pull_request:
    branches:
      - Docker
  schedule:
    - cron: '30 07 * * *'
    - cron: '20 18 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  predict:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run prediction
        run: python scripts/prediction-api-script.py

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Extract prediction data and set environment variables
        run: |
          PREDICTION_DATE=$(jq -r '.date' data/predictions/latest.json)
          PREDICTION_TIME=$(jq -r '.time' data/predictions/latest.json)
          PREDICTED_SPECIES=$(jq -r '.predicted_species' data/predictions/latest.json)
          PREDICTION_NOTE=$(jq -r '.note' data/predictions/latest.json)
          BILL_LENGTH=$(jq -r '.penguin_data.bill_length_mm' data/predictions/latest.json)
          BILL_DEPTH=$(jq -r '.penguin_data.bill_depth_mm' data/predictions/latest.json)
          FLIPPER_LENGTH=$(jq -r '.penguin_data.flipper_length_mm' data/predictions/latest.json)
          BODY_MASS=$(jq -r '.penguin_data.body_mass_g' data/predictions/latest.json)
          echo "PREDICTION_DATE=$PREDICTION_DATE" >> $GITHUB_ENV
          echo "PREDICTION_TIME=$PREDICTION_TIME" >> $GITHUB_ENV
          echo "PREDICTED_SPECIES=$PREDICTED_SPECIES" >> $GITHUB_ENV
          echo "PREDICTION_NOTE=$PREDICTION_NOTE" >> $GITHUB_ENV
          echo "BILL_LENGTH=$BILL_LENGTH" >> $GITHUB_ENV
          echo "BILL_DEPTH=$BILL_DEPTH" >> $GITHUB_ENV
          echo "FLIPPER_LENGTH=$FLIPPER_LENGTH" >> $GITHUB_ENV
          echo "BODY_MASS=$BODY_MASS" >> $GITHUB_ENV

      - name: Generate index.html from template
        run: envsubst < templates/index.html.template > index.html

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot
::contentReference[oaicite:21]{index=21}
 
