name: Daily Penguin Prediction

on:
  push:
    branches:
      - Docker
  pull_request:
    branches:
      - Docker
  schedule:
    # Run at 6:20 PM UTC every day
    - cron: '30 07 * * *'
    - cron: '20 18 * * *'
  workflow_dispatch:

permissions:
  contents: write  # Explicit permission to write to repository contents

jobs:
  predict:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run prediction
        run: |
          python scripts/prediction-api-script.py

      - name: Copy files for GitHub Pages
        run: |
          cp data/predictions/index.html ./index.html || true
          cp data/predictions/latest_visualization.png ./latest_visualization.png || true
          cp data/predictions/latest.json ./latest.json || true
          cp data/predictions/history.json ./history.json || true
          # Create a .nojekyll file to disable Jekyll processing
          touch .nojekyll

      - name: Commit and push
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          # Add all the files
          git add .nojekyll || true
          git add index.html || true
          git add latest_visualization.png || true
          git add latest.json || true
          git add history.json || true
          git add data/predictions/* || true
          # Commit if there are changes
          git diff --staged --quiet || git commit -m "Update penguin prediction for $(date +'%Y-%m-%d')"
          # Push changes to GitHub
          git push || (git pull --rebase && git push)
